//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SIFCA_DAL
{
    public partial class LINEANOMADERABLES
    {
        public LINEANOMADERABLES()
        {
            this.TIPODEUSO = new HashSet<TIPODEUSO>();
        }
    
        public System.Guid LINEANMAD { get; set; }
        public System.Guid NROFORMULARIO { get; set; }
        public string OBSERVACIONES { get; set; }
    
        public virtual FORMULARIO FORMULARIO { get; set; }
        public virtual ICollection<TIPODEUSO> TIPODEUSO { get; set; }
    }
    
}
