//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SIFCA_DAL
{
    public partial class LISTADODEESPECIES
    {
        public LISTADODEESPECIES()
        {
            this.PROYECTO = new HashSet<PROYECTO>();
            this.ESPECIE = new HashSet<ESPECIE>();
        }
    
        public string NOMARCH { get; set; }
        public string DESCRIPLISTESPECIES { get; set; }
    
        public virtual ICollection<PROYECTO> PROYECTO { get; set; }
        public virtual ICollection<ESPECIE> ESPECIE { get; set; }
    }
    
}
