//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SIFCA_DAL
{
    public partial class PROYECTO
    {
        public PROYECTO()
        {
            this.INVENTARIO = new HashSet<INVENTARIO>();
            this.REGENERACION = new HashSet<REGENERACION>();
        }
    
        public decimal NROPROY { get; set; }
        public System.Guid NROEST { get; set; }
        public string NOMBRETIPOINV { get; set; }
        public string NOMARCH { get; set; }
        public string LUGAR { get; set; }
        public decimal SUPTOT { get; set; }
        public decimal INTMUE { get; set; }
        public decimal SUPMUE { get; set; }
        public decimal TAMANO { get; set; }
        public decimal LIMTSUPDAP { get; set; }
        public decimal LIMTINFDAP { get; set; }
        public decimal FACTORDEFORMA { get; set; }
        public decimal AREAFUSTALESPORPARCELA { get; set; }
        public string ESTADOPROY { get; set; }
    
        public virtual ICollection<INVENTARIO> INVENTARIO { get; set; }
        public virtual LISTADODEESPECIES LISTADODEESPECIES { get; set; }
        public virtual TIPOINVENTARIO TIPOINVENTARIO { get; set; }
        public virtual ICollection<REGENERACION> REGENERACION { get; set; }
    }
    
}
