//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SIFCA_DAL
{
    public partial class PROYECTO
    {
        public PROYECTO()
        {
            this.FORMULARIO = new HashSet<FORMULARIO>();
            this.LISTADODEESTRATOS = new HashSet<LISTADODEESTRATOS>();
            this.ESPECIE = new HashSet<ESPECIE>();
            this.PROYECTO1 = new HashSet<PROYECTO>();
            this.PROYECTO2 = new HashSet<PROYECTO>();
        }
    
        public System.Guid NROPROY { get; set; }
        public System.Guid NROUSUARIO { get; set; }
        public decimal TIPOPOYECTO_ID { get; set; }
        public string NOMBRETIPOINV { get; set; }
        public string NOMTIPODISEMUEST { get; set; }
        public string LUGAR { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal SUPTOT { get; set; }
        public decimal INTMUE { get; set; }
        public decimal SUPMUE { get; set; }
        public decimal TAMANO { get; set; }
        public decimal LIMITINFDAP { get; set; }
        public decimal LIMITSUPDAP { get; set; }
        public decimal AREAFUSTALESPORPARCELA { get; set; }
        public decimal FACTORDEFORMA { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<decimal> NUMEROETAPAS { get; set; }
    
        public virtual ICollection<FORMULARIO> FORMULARIO { get; set; }
        public virtual ICollection<LISTADODEESTRATOS> LISTADODEESTRATOS { get; set; }
        public virtual OBJETIVOINVENTARIO OBJETIVOINVENTARIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual TIPOPROYECTO TIPOPROYECTO { get; set; }
        public virtual TIPODISENOMUESTRAL TIPODISENOMUESTRAL { get; set; }
        public virtual ICollection<ESPECIE> ESPECIE { get; set; }
        public virtual ICollection<PROYECTO> PROYECTO1 { get; set; }
        public virtual ICollection<PROYECTO> PROYECTO2 { get; set; }
    }
    
}
