
-- --------------------------------------------------
-- Entity Designer DDL Script for SQL Server 2005, 2008, and Azure
-- --------------------------------------------------
-- Date Created: 09/09/2013 14:19:40
-- Generated from EDMX file: C:\Users\Victacora\Desktop\ANTEPROYECTO\Prototipo\App\SIFCA_DAL\SIFCA_Model.edmx
-- --------------------------------------------------

SET QUOTED_IDENTIFIER OFF;
GO
USE [SIFCA_BD];
GO
IF SCHEMA_ID(N'dbo') IS NULL EXECUTE(N'CREATE SCHEMA [dbo]');
GO

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[FK_LINEAINV_POSEE_CALIDAD]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[LINEAINVENTARIO] DROP CONSTRAINT [FK_LINEAINV_POSEE_CALIDAD];
GO
IF OBJECT_ID(N'[dbo].[FK_ESPECIE_PERTENECE_GRUPOCOM]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ESPECIE] DROP CONSTRAINT [FK_ESPECIE_PERTENECE_GRUPOCOM];
GO
IF OBJECT_ID(N'[dbo].[FK_LINEAINV_CONTIENE_ESPECIE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[LINEAINVENTARIO] DROP CONSTRAINT [FK_LINEAINV_CONTIENE_ESPECIE];
GO
IF OBJECT_ID(N'[dbo].[FK_LINEAREG_EVALUACIO_ESPECIE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[LINEAREGENERACION] DROP CONSTRAINT [FK_LINEAREG_EVALUACIO_ESPECIE];
GO
IF OBJECT_ID(N'[dbo].[FK_LINEAINV_ASOCIADO_ESTADOSA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[LINEAINVENTARIO] DROP CONSTRAINT [FK_LINEAINV_ASOCIADO_ESTADOSA];
GO
IF OBJECT_ID(N'[dbo].[FK_FORMULAR_MANEJA_ESTRATO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[FORMULARIO] DROP CONSTRAINT [FK_FORMULAR_MANEJA_ESTRATO];
GO
IF OBJECT_ID(N'[dbo].[FK_LISTADOD_LISTESTRA_ESTRATO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[LISTADODEESTRATOS] DROP CONSTRAINT [FK_LISTADOD_LISTESTRA_ESTRATO];
GO
IF OBJECT_ID(N'[dbo].[FK_FORMULAR_DESARROLL_PROYECTO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[FORMULARIO] DROP CONSTRAINT [FK_FORMULAR_DESARROLL_PROYECTO];
GO
IF OBJECT_ID(N'[dbo].[FK_FORMULAR_ES_DE_TIPOFORM]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[FORMULARIO] DROP CONSTRAINT [FK_FORMULAR_ES_DE_TIPOFORM];
GO
IF OBJECT_ID(N'[dbo].[FK_FORMULAR_ES_REPONS_USUARIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[FORMULARIO] DROP CONSTRAINT [FK_FORMULAR_ES_REPONS_USUARIO];
GO
IF OBJECT_ID(N'[dbo].[FK_LINEAINV_LLENA_FORMULAR]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[LINEAINVENTARIO] DROP CONSTRAINT [FK_LINEAINV_LLENA_FORMULAR];
GO
IF OBJECT_ID(N'[dbo].[FK_LINEANOM_RECOLECTA_FORMULAR]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[LINEANOMADERABLES] DROP CONSTRAINT [FK_LINEANOM_RECOLECTA_FORMULAR];
GO
IF OBJECT_ID(N'[dbo].[FK_LINEAREG_COMPLETA_FORMULAR]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[LINEAREGENERACION] DROP CONSTRAINT [FK_LINEAREG_COMPLETA_FORMULAR];
GO
IF OBJECT_ID(N'[dbo].[FK_LISTADOD_LISTESTRA_PROYECTO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[LISTADODEESTRATOS] DROP CONSTRAINT [FK_LISTADOD_LISTESTRA_PROYECTO];
GO
IF OBJECT_ID(N'[dbo].[FK_PROYECTO_ES_OBJETIVO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PROYECTO] DROP CONSTRAINT [FK_PROYECTO_ES_OBJETIVO];
GO
IF OBJECT_ID(N'[dbo].[FK_PROYECTO_CREA_USUARIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PROYECTO] DROP CONSTRAINT [FK_PROYECTO_CREA_USUARIO];
GO
IF OBJECT_ID(N'[dbo].[FK_PROYECTO_ES_DE_TIP_TIPOPROY]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PROYECTO] DROP CONSTRAINT [FK_PROYECTO_ES_DE_TIP_TIPOPROY];
GO
IF OBJECT_ID(N'[dbo].[FK_PROYECTO_REALIZA_TIPODISE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PROYECTO] DROP CONSTRAINT [FK_PROYECTO_REALIZA_TIPODISE];
GO
IF OBJECT_ID(N'[dbo].[FK_TRANSACC_REGISTRA_USUARIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TRANSACCION] DROP CONSTRAINT [FK_TRANSACC_REGISTRA_USUARIO];
GO
IF OBJECT_ID(N'[dbo].[FK_LISTADODEESPECIES_ESPECIE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[LISTADODEESPECIES] DROP CONSTRAINT [FK_LISTADODEESPECIES_ESPECIE];
GO
IF OBJECT_ID(N'[dbo].[FK_LISTADODEESPECIES_PROYECTO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[LISTADODEESPECIES] DROP CONSTRAINT [FK_LISTADODEESPECIES_PROYECTO];
GO
IF OBJECT_ID(N'[dbo].[FK_PROYECTOSPORETAPA_PROYECTO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PROYECTOSPORETAPA] DROP CONSTRAINT [FK_PROYECTOSPORETAPA_PROYECTO];
GO
IF OBJECT_ID(N'[dbo].[FK_PROYECTOSPORETAPA_PROYECTO1]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PROYECTOSPORETAPA] DROP CONSTRAINT [FK_PROYECTOSPORETAPA_PROYECTO1];
GO
IF OBJECT_ID(N'[dbo].[FK_USO_LINEANOMADERABLES]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[USO] DROP CONSTRAINT [FK_USO_LINEANOMADERABLES];
GO
IF OBJECT_ID(N'[dbo].[FK_USO_TIPODEUSO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[USO] DROP CONSTRAINT [FK_USO_TIPODEUSO];
GO

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[CALIDAD]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CALIDAD];
GO
IF OBJECT_ID(N'[dbo].[ESPECIE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[ESPECIE];
GO
IF OBJECT_ID(N'[dbo].[ESTADOSANITARIO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[ESTADOSANITARIO];
GO
IF OBJECT_ID(N'[dbo].[ESTRATO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[ESTRATO];
GO
IF OBJECT_ID(N'[dbo].[FORMULARIO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[FORMULARIO];
GO
IF OBJECT_ID(N'[dbo].[GRUPOCOMERCIAL]', 'U') IS NOT NULL
    DROP TABLE [dbo].[GRUPOCOMERCIAL];
GO
IF OBJECT_ID(N'[dbo].[LINEAINVENTARIO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[LINEAINVENTARIO];
GO
IF OBJECT_ID(N'[dbo].[LINEANOMADERABLES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[LINEANOMADERABLES];
GO
IF OBJECT_ID(N'[dbo].[LINEAREGENERACION]', 'U') IS NOT NULL
    DROP TABLE [dbo].[LINEAREGENERACION];
GO
IF OBJECT_ID(N'[dbo].[LISTADODEESTRATOS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[LISTADODEESTRATOS];
GO
IF OBJECT_ID(N'[dbo].[OBJETIVOINVENTARIO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[OBJETIVOINVENTARIO];
GO
IF OBJECT_ID(N'[dbo].[PROYECTO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PROYECTO];
GO
IF OBJECT_ID(N'[dbo].[TIPODEUSO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TIPODEUSO];
GO
IF OBJECT_ID(N'[dbo].[TIPODISENOMUESTRAL]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TIPODISENOMUESTRAL];
GO
IF OBJECT_ID(N'[dbo].[TIPOFORMULARIO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TIPOFORMULARIO];
GO
IF OBJECT_ID(N'[dbo].[TIPOPROYECTO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TIPOPROYECTO];
GO
IF OBJECT_ID(N'[dbo].[TRANSACCION]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TRANSACCION];
GO
IF OBJECT_ID(N'[dbo].[TSTUDENT]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TSTUDENT];
GO
IF OBJECT_ID(N'[dbo].[USUARIO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[USUARIO];
GO
IF OBJECT_ID(N'[dbo].[LISTADODEESPECIES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[LISTADODEESPECIES];
GO
IF OBJECT_ID(N'[dbo].[PROYECTOSPORETAPA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PROYECTOSPORETAPA];
GO
IF OBJECT_ID(N'[dbo].[USO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[USO];
GO

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'CALIDAD'
CREATE TABLE [dbo].[CALIDAD] (
    [CODCALIDAD] decimal(18,0) IDENTITY(1,1) NOT NULL,
    [DESCRIPCALIDAD] varchar(500)  NULL
);
GO

-- Creating table 'ESPECIE'
CREATE TABLE [dbo].[ESPECIE] (
    [CODESP] uniqueidentifier  NOT NULL,
    [GRUPOCOM] char(2)  NOT NULL,
    [NOMCOMUN] varchar(200)  NULL,
    [NOMCIENTIFICO] varchar(200)  NULL,
    [FAMILIA] varchar(200)  NULL,
    [ZONAGEOGRAFICA] varchar(200)  NULL,
    [ZONADEVIDA] varchar(200)  NULL,
    [DIAMMINCORTE] decimal(18,0)  NULL
);
GO

-- Creating table 'ESTADOSANITARIO'
CREATE TABLE [dbo].[ESTADOSANITARIO] (
    [ESTADO] char(2)  NOT NULL,
    [DESCRIPESTADO] varchar(500)  NULL
);
GO

-- Creating table 'ESTRATO'
CREATE TABLE [dbo].[ESTRATO] (
    [CODEST] decimal(18,0) IDENTITY(1,1) NOT NULL,
    [DESCRIPESTRATO] varchar(500)  NULL
);
GO

-- Creating table 'FORMULARIO'
CREATE TABLE [dbo].[FORMULARIO] (
    [NROFORMULARIO] uniqueidentifier  NOT NULL,
    [TIPFORM_ID] decimal(18,0)  NOT NULL,
    [CODEST] decimal(18,0)  NOT NULL,
    [NROUSUARIO] uniqueidentifier  NOT NULL,
    [NROPROY] uniqueidentifier  NOT NULL,
    [FECHACREACION] datetime  NOT NULL,
    [HORAINICIO] datetime  NOT NULL,
    [HORAFINAL] datetime  NOT NULL,
    [PARCELA] decimal(18,0)  NOT NULL,
    [LINEA] decimal(18,0)  NOT NULL,
    [COORDENADAX] decimal(18,0)  NULL,
    [COORDENADAY] decimal(18,0)  NULL
);
GO

-- Creating table 'GRUPOCOMERCIAL'
CREATE TABLE [dbo].[GRUPOCOMERCIAL] (
    [GRUPOCOM] char(2)  NOT NULL,
    [DESCRIPGRUPO] varchar(500)  NULL
);
GO

-- Creating table 'LINEAINVENTARIO'
CREATE TABLE [dbo].[LINEAINVENTARIO] (
    [LINEAINV] uniqueidentifier  NOT NULL,
    [CODCALIDAD] decimal(18,0)  NOT NULL,
    [ESTADO] char(2)  NOT NULL,
    [CODESP] uniqueidentifier  NOT NULL,
    [NROFORMULARIO] uniqueidentifier  NOT NULL,
    [NROARB] decimal(18,0)  NULL,
    [CAP] decimal(18,0)  NULL,
    [DAP] decimal(18,0)  NULL,
    [ALTCOMER_M] decimal(18,0)  NULL,
    [ALTTOT_M] decimal(18,0)  NULL,
    [AREABASAL] decimal(18,3)  NULL,
    [VOLCOM] decimal(18,3)  NULL,
    [VOLTOT] decimal(18,3)  NULL
);
GO

-- Creating table 'LINEANOMADERABLES'
CREATE TABLE [dbo].[LINEANOMADERABLES] (
    [LINEANMAD] uniqueidentifier  NOT NULL,
    [NROFORMULARIO] uniqueidentifier  NOT NULL,
    [OBSERVACIONES] varchar(500)  NULL
);
GO

-- Creating table 'LINEAREGENERACION'
CREATE TABLE [dbo].[LINEAREGENERACION] (
    [NROARB] decimal(18,0)  NULL,
    [LATIZAL] decimal(18,0)  NULL,
    [BRINZAL] decimal(18,0)  NULL,
    [LINEAREGEN] uniqueidentifier  NOT NULL,
    [CODESP] uniqueidentifier  NOT NULL,
    [NROFORMULARIO] uniqueidentifier  NOT NULL
);
GO

-- Creating table 'LISTADODEESTRATOS'
CREATE TABLE [dbo].[LISTADODEESTRATOS] (
    [NROPROY] uniqueidentifier  NOT NULL,
    [CODEST] decimal(18,0)  NOT NULL,
    [PESO] decimal(18,3)  NULL
);
GO

-- Creating table 'OBJETIVOINVENTARIO'
CREATE TABLE [dbo].[OBJETIVOINVENTARIO] (
    [NOMBRETIPOINV] varchar(100)  NOT NULL,
    [DESCRIPOBJETINV] varchar(500)  NULL
);
GO

-- Creating table 'PROYECTO'
CREATE TABLE [dbo].[PROYECTO] (
    [NROPROY] uniqueidentifier  NOT NULL,
    [NROUSUARIO] uniqueidentifier  NOT NULL,
    [TIPOPOYECTO_ID] decimal(18,0)  NOT NULL,
    [NOMBRETIPOINV] varchar(100)  NOT NULL,
    [NOMTIPODISEMUEST] varchar(100)  NOT NULL,
    [LUGAR] varchar(100)  NOT NULL,
    [DESCRIPCION] varchar(500)  NULL,
    [SUPTOT] decimal(18,3)  NOT NULL,
    [INTMUE] decimal(18,3)  NOT NULL,
    [SUPMUE] decimal(18,3)  NOT NULL,
    [TAMANO] decimal(18,3)  NOT NULL,
    [LIMITINFDAP] decimal(18,3)  NOT NULL,
    [LIMITSUPDAP] decimal(18,3)  NOT NULL,
    [AREAFUSTALESPORPARCELA] decimal(18,3)  NOT NULL,
    [FACTORDEFORMA] decimal(18,3)  NOT NULL,
    [FECHA] datetime  NOT NULL,
    [NUMEROETAPAS] decimal(18,0)  NULL
);
GO

-- Creating table 'TIPODEUSO'
CREATE TABLE [dbo].[TIPODEUSO] (
    [NOMBRETIPOUSO] varchar(100)  NOT NULL,
    [DESCRIPCION] varchar(500)  NULL
);
GO

-- Creating table 'TIPODISENOMUESTRAL'
CREATE TABLE [dbo].[TIPODISENOMUESTRAL] (
    [NOMTIPODISEMUEST] varchar(100)  NOT NULL,
    [DESCRIPTIPODISEMUEST] varchar(500)  NULL
);
GO

-- Creating table 'TIPOFORMULARIO'
CREATE TABLE [dbo].[TIPOFORMULARIO] (
    [NOMBRETIPOFORM] varchar(100)  NOT NULL,
    [DESCRIPCION] varchar(500)  NULL,
    [TIPFORM_ID] decimal(18,0) IDENTITY(1,1) NOT NULL
);
GO

-- Creating table 'TIPOPROYECTO'
CREATE TABLE [dbo].[TIPOPROYECTO] (
    [TIPOPROYECTO_ID] decimal(18,0)  NOT NULL,
    [DESCRIPCION] varchar(500)  NOT NULL,
    [NOMBRETIPOPROYECTO] varchar(100)  NULL
);
GO

-- Creating table 'TRANSACCION'
CREATE TABLE [dbo].[TRANSACCION] (
    [NROTRANS] uniqueidentifier  NOT NULL,
    [NROUSUARIO] uniqueidentifier  NOT NULL,
    [FECHA] datetime  NOT NULL,
    [TABLA] varchar(100)  NOT NULL,
    [IDREGISTRO] decimal(18,0)  NOT NULL,
    [OPERACION] char(1)  NOT NULL,
    [VALORESVIEJOS] varchar(1024)  NULL,
    [VALORESNUEVOS] varchar(1024)  NULL
);
GO

-- Creating table 'TSTUDENT'
CREATE TABLE [dbo].[TSTUDENT] (
    [N] decimal(18,0)  NOT NULL,
    [ALPHA] decimal(18,3)  NOT NULL,
    [VALOR] decimal(18,3)  NOT NULL
);
GO

-- Creating table 'USUARIO'
CREATE TABLE [dbo].[USUARIO] (
    [NROUSUARIO] uniqueidentifier  NOT NULL,
    [NOMBRES] varchar(100)  NOT NULL,
    [APELLIDOS] varchar(100)  NOT NULL,
    [USUARIO1] varchar(100)  NOT NULL,
    [CONTRASENA] varchar(1000)  NOT NULL,
    [CEDULA] decimal(18,0)  NOT NULL
);
GO

-- Creating table 'LISTADODEESPECIES'
CREATE TABLE [dbo].[LISTADODEESPECIES] (
    [ESPECIE_CODESP] uniqueidentifier  NOT NULL,
    [PROYECTO_NROPROY] uniqueidentifier  NOT NULL
);
GO

-- Creating table 'PROYECTOSPORETAPA'
CREATE TABLE [dbo].[PROYECTOSPORETAPA] (
    [PROYECTOCONTENIDO_NROPROY] uniqueidentifier  NOT NULL,
    [PROYECTOCONTENDOR_NROPROY] uniqueidentifier  NOT NULL
);
GO

-- Creating table 'USO'
CREATE TABLE [dbo].[USO] (
    [LINEANOMADERABLES_LINEANMAD] uniqueidentifier  NOT NULL,
    [TIPODEUSO_NOMBRETIPOUSO] varchar(100)  NOT NULL
);
GO

-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on [CODCALIDAD] in table 'CALIDAD'
ALTER TABLE [dbo].[CALIDAD]
ADD CONSTRAINT [PK_CALIDAD]
    PRIMARY KEY CLUSTERED ([CODCALIDAD] ASC);
GO

-- Creating primary key on [CODESP] in table 'ESPECIE'
ALTER TABLE [dbo].[ESPECIE]
ADD CONSTRAINT [PK_ESPECIE]
    PRIMARY KEY CLUSTERED ([CODESP] ASC);
GO

-- Creating primary key on [ESTADO] in table 'ESTADOSANITARIO'
ALTER TABLE [dbo].[ESTADOSANITARIO]
ADD CONSTRAINT [PK_ESTADOSANITARIO]
    PRIMARY KEY CLUSTERED ([ESTADO] ASC);
GO

-- Creating primary key on [CODEST] in table 'ESTRATO'
ALTER TABLE [dbo].[ESTRATO]
ADD CONSTRAINT [PK_ESTRATO]
    PRIMARY KEY CLUSTERED ([CODEST] ASC);
GO

-- Creating primary key on [NROFORMULARIO] in table 'FORMULARIO'
ALTER TABLE [dbo].[FORMULARIO]
ADD CONSTRAINT [PK_FORMULARIO]
    PRIMARY KEY CLUSTERED ([NROFORMULARIO] ASC);
GO

-- Creating primary key on [GRUPOCOM] in table 'GRUPOCOMERCIAL'
ALTER TABLE [dbo].[GRUPOCOMERCIAL]
ADD CONSTRAINT [PK_GRUPOCOMERCIAL]
    PRIMARY KEY CLUSTERED ([GRUPOCOM] ASC);
GO

-- Creating primary key on [LINEAINV] in table 'LINEAINVENTARIO'
ALTER TABLE [dbo].[LINEAINVENTARIO]
ADD CONSTRAINT [PK_LINEAINVENTARIO]
    PRIMARY KEY CLUSTERED ([LINEAINV] ASC);
GO

-- Creating primary key on [LINEANMAD] in table 'LINEANOMADERABLES'
ALTER TABLE [dbo].[LINEANOMADERABLES]
ADD CONSTRAINT [PK_LINEANOMADERABLES]
    PRIMARY KEY CLUSTERED ([LINEANMAD] ASC);
GO

-- Creating primary key on [LINEAREGEN] in table 'LINEAREGENERACION'
ALTER TABLE [dbo].[LINEAREGENERACION]
ADD CONSTRAINT [PK_LINEAREGENERACION]
    PRIMARY KEY CLUSTERED ([LINEAREGEN] ASC);
GO

-- Creating primary key on [NROPROY], [CODEST] in table 'LISTADODEESTRATOS'
ALTER TABLE [dbo].[LISTADODEESTRATOS]
ADD CONSTRAINT [PK_LISTADODEESTRATOS]
    PRIMARY KEY CLUSTERED ([NROPROY], [CODEST] ASC);
GO

-- Creating primary key on [NOMBRETIPOINV] in table 'OBJETIVOINVENTARIO'
ALTER TABLE [dbo].[OBJETIVOINVENTARIO]
ADD CONSTRAINT [PK_OBJETIVOINVENTARIO]
    PRIMARY KEY CLUSTERED ([NOMBRETIPOINV] ASC);
GO

-- Creating primary key on [NROPROY] in table 'PROYECTO'
ALTER TABLE [dbo].[PROYECTO]
ADD CONSTRAINT [PK_PROYECTO]
    PRIMARY KEY CLUSTERED ([NROPROY] ASC);
GO

-- Creating primary key on [NOMBRETIPOUSO] in table 'TIPODEUSO'
ALTER TABLE [dbo].[TIPODEUSO]
ADD CONSTRAINT [PK_TIPODEUSO]
    PRIMARY KEY CLUSTERED ([NOMBRETIPOUSO] ASC);
GO

-- Creating primary key on [NOMTIPODISEMUEST] in table 'TIPODISENOMUESTRAL'
ALTER TABLE [dbo].[TIPODISENOMUESTRAL]
ADD CONSTRAINT [PK_TIPODISENOMUESTRAL]
    PRIMARY KEY CLUSTERED ([NOMTIPODISEMUEST] ASC);
GO

-- Creating primary key on [TIPFORM_ID] in table 'TIPOFORMULARIO'
ALTER TABLE [dbo].[TIPOFORMULARIO]
ADD CONSTRAINT [PK_TIPOFORMULARIO]
    PRIMARY KEY CLUSTERED ([TIPFORM_ID] ASC);
GO

-- Creating primary key on [TIPOPROYECTO_ID] in table 'TIPOPROYECTO'
ALTER TABLE [dbo].[TIPOPROYECTO]
ADD CONSTRAINT [PK_TIPOPROYECTO]
    PRIMARY KEY CLUSTERED ([TIPOPROYECTO_ID] ASC);
GO

-- Creating primary key on [NROTRANS] in table 'TRANSACCION'
ALTER TABLE [dbo].[TRANSACCION]
ADD CONSTRAINT [PK_TRANSACCION]
    PRIMARY KEY CLUSTERED ([NROTRANS] ASC);
GO

-- Creating primary key on [N], [ALPHA], [VALOR] in table 'TSTUDENT'
ALTER TABLE [dbo].[TSTUDENT]
ADD CONSTRAINT [PK_TSTUDENT]
    PRIMARY KEY CLUSTERED ([N], [ALPHA], [VALOR] ASC);
GO

-- Creating primary key on [NROUSUARIO] in table 'USUARIO'
ALTER TABLE [dbo].[USUARIO]
ADD CONSTRAINT [PK_USUARIO]
    PRIMARY KEY CLUSTERED ([NROUSUARIO] ASC);
GO

-- Creating primary key on [ESPECIE_CODESP], [PROYECTO_NROPROY] in table 'LISTADODEESPECIES'
ALTER TABLE [dbo].[LISTADODEESPECIES]
ADD CONSTRAINT [PK_LISTADODEESPECIES]
    PRIMARY KEY NONCLUSTERED ([ESPECIE_CODESP], [PROYECTO_NROPROY] ASC);
GO

-- Creating primary key on [PROYECTOCONTENIDO_NROPROY], [PROYECTOCONTENDOR_NROPROY] in table 'PROYECTOSPORETAPA'
ALTER TABLE [dbo].[PROYECTOSPORETAPA]
ADD CONSTRAINT [PK_PROYECTOSPORETAPA]
    PRIMARY KEY NONCLUSTERED ([PROYECTOCONTENIDO_NROPROY], [PROYECTOCONTENDOR_NROPROY] ASC);
GO

-- Creating primary key on [LINEANOMADERABLES_LINEANMAD], [TIPODEUSO_NOMBRETIPOUSO] in table 'USO'
ALTER TABLE [dbo].[USO]
ADD CONSTRAINT [PK_USO]
    PRIMARY KEY NONCLUSTERED ([LINEANOMADERABLES_LINEANMAD], [TIPODEUSO_NOMBRETIPOUSO] ASC);
GO

-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on [CODCALIDAD] in table 'LINEAINVENTARIO'
ALTER TABLE [dbo].[LINEAINVENTARIO]
ADD CONSTRAINT [FK_LINEAINV_POSEE_CALIDAD]
    FOREIGN KEY ([CODCALIDAD])
    REFERENCES [dbo].[CALIDAD]
        ([CODCALIDAD])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_LINEAINV_POSEE_CALIDAD'
CREATE INDEX [IX_FK_LINEAINV_POSEE_CALIDAD]
ON [dbo].[LINEAINVENTARIO]
    ([CODCALIDAD]);
GO

-- Creating foreign key on [GRUPOCOM] in table 'ESPECIE'
ALTER TABLE [dbo].[ESPECIE]
ADD CONSTRAINT [FK_ESPECIE_PERTENECE_GRUPOCOM]
    FOREIGN KEY ([GRUPOCOM])
    REFERENCES [dbo].[GRUPOCOMERCIAL]
        ([GRUPOCOM])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_ESPECIE_PERTENECE_GRUPOCOM'
CREATE INDEX [IX_FK_ESPECIE_PERTENECE_GRUPOCOM]
ON [dbo].[ESPECIE]
    ([GRUPOCOM]);
GO

-- Creating foreign key on [CODESP] in table 'LINEAINVENTARIO'
ALTER TABLE [dbo].[LINEAINVENTARIO]
ADD CONSTRAINT [FK_LINEAINV_CONTIENE_ESPECIE]
    FOREIGN KEY ([CODESP])
    REFERENCES [dbo].[ESPECIE]
        ([CODESP])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_LINEAINV_CONTIENE_ESPECIE'
CREATE INDEX [IX_FK_LINEAINV_CONTIENE_ESPECIE]
ON [dbo].[LINEAINVENTARIO]
    ([CODESP]);
GO

-- Creating foreign key on [CODESP] in table 'LINEAREGENERACION'
ALTER TABLE [dbo].[LINEAREGENERACION]
ADD CONSTRAINT [FK_LINEAREG_EVALUACIO_ESPECIE]
    FOREIGN KEY ([CODESP])
    REFERENCES [dbo].[ESPECIE]
        ([CODESP])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_LINEAREG_EVALUACIO_ESPECIE'
CREATE INDEX [IX_FK_LINEAREG_EVALUACIO_ESPECIE]
ON [dbo].[LINEAREGENERACION]
    ([CODESP]);
GO

-- Creating foreign key on [ESTADO] in table 'LINEAINVENTARIO'
ALTER TABLE [dbo].[LINEAINVENTARIO]
ADD CONSTRAINT [FK_LINEAINV_ASOCIADO_ESTADOSA]
    FOREIGN KEY ([ESTADO])
    REFERENCES [dbo].[ESTADOSANITARIO]
        ([ESTADO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_LINEAINV_ASOCIADO_ESTADOSA'
CREATE INDEX [IX_FK_LINEAINV_ASOCIADO_ESTADOSA]
ON [dbo].[LINEAINVENTARIO]
    ([ESTADO]);
GO

-- Creating foreign key on [CODEST] in table 'FORMULARIO'
ALTER TABLE [dbo].[FORMULARIO]
ADD CONSTRAINT [FK_FORMULAR_MANEJA_ESTRATO]
    FOREIGN KEY ([CODEST])
    REFERENCES [dbo].[ESTRATO]
        ([CODEST])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_FORMULAR_MANEJA_ESTRATO'
CREATE INDEX [IX_FK_FORMULAR_MANEJA_ESTRATO]
ON [dbo].[FORMULARIO]
    ([CODEST]);
GO

-- Creating foreign key on [CODEST] in table 'LISTADODEESTRATOS'
ALTER TABLE [dbo].[LISTADODEESTRATOS]
ADD CONSTRAINT [FK_LISTADOD_LISTESTRA_ESTRATO]
    FOREIGN KEY ([CODEST])
    REFERENCES [dbo].[ESTRATO]
        ([CODEST])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_LISTADOD_LISTESTRA_ESTRATO'
CREATE INDEX [IX_FK_LISTADOD_LISTESTRA_ESTRATO]
ON [dbo].[LISTADODEESTRATOS]
    ([CODEST]);
GO

-- Creating foreign key on [NROPROY] in table 'FORMULARIO'
ALTER TABLE [dbo].[FORMULARIO]
ADD CONSTRAINT [FK_FORMULAR_DESARROLL_PROYECTO]
    FOREIGN KEY ([NROPROY])
    REFERENCES [dbo].[PROYECTO]
        ([NROPROY])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_FORMULAR_DESARROLL_PROYECTO'
CREATE INDEX [IX_FK_FORMULAR_DESARROLL_PROYECTO]
ON [dbo].[FORMULARIO]
    ([NROPROY]);
GO

-- Creating foreign key on [TIPFORM_ID] in table 'FORMULARIO'
ALTER TABLE [dbo].[FORMULARIO]
ADD CONSTRAINT [FK_FORMULAR_ES_DE_TIPOFORM]
    FOREIGN KEY ([TIPFORM_ID])
    REFERENCES [dbo].[TIPOFORMULARIO]
        ([TIPFORM_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_FORMULAR_ES_DE_TIPOFORM'
CREATE INDEX [IX_FK_FORMULAR_ES_DE_TIPOFORM]
ON [dbo].[FORMULARIO]
    ([TIPFORM_ID]);
GO

-- Creating foreign key on [NROUSUARIO] in table 'FORMULARIO'
ALTER TABLE [dbo].[FORMULARIO]
ADD CONSTRAINT [FK_FORMULAR_ES_REPONS_USUARIO]
    FOREIGN KEY ([NROUSUARIO])
    REFERENCES [dbo].[USUARIO]
        ([NROUSUARIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_FORMULAR_ES_REPONS_USUARIO'
CREATE INDEX [IX_FK_FORMULAR_ES_REPONS_USUARIO]
ON [dbo].[FORMULARIO]
    ([NROUSUARIO]);
GO

-- Creating foreign key on [NROFORMULARIO] in table 'LINEAINVENTARIO'
ALTER TABLE [dbo].[LINEAINVENTARIO]
ADD CONSTRAINT [FK_LINEAINV_LLENA_FORMULAR]
    FOREIGN KEY ([NROFORMULARIO])
    REFERENCES [dbo].[FORMULARIO]
        ([NROFORMULARIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_LINEAINV_LLENA_FORMULAR'
CREATE INDEX [IX_FK_LINEAINV_LLENA_FORMULAR]
ON [dbo].[LINEAINVENTARIO]
    ([NROFORMULARIO]);
GO

-- Creating foreign key on [NROFORMULARIO] in table 'LINEANOMADERABLES'
ALTER TABLE [dbo].[LINEANOMADERABLES]
ADD CONSTRAINT [FK_LINEANOM_RECOLECTA_FORMULAR]
    FOREIGN KEY ([NROFORMULARIO])
    REFERENCES [dbo].[FORMULARIO]
        ([NROFORMULARIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_LINEANOM_RECOLECTA_FORMULAR'
CREATE INDEX [IX_FK_LINEANOM_RECOLECTA_FORMULAR]
ON [dbo].[LINEANOMADERABLES]
    ([NROFORMULARIO]);
GO

-- Creating foreign key on [NROFORMULARIO] in table 'LINEAREGENERACION'
ALTER TABLE [dbo].[LINEAREGENERACION]
ADD CONSTRAINT [FK_LINEAREG_COMPLETA_FORMULAR]
    FOREIGN KEY ([NROFORMULARIO])
    REFERENCES [dbo].[FORMULARIO]
        ([NROFORMULARIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_LINEAREG_COMPLETA_FORMULAR'
CREATE INDEX [IX_FK_LINEAREG_COMPLETA_FORMULAR]
ON [dbo].[LINEAREGENERACION]
    ([NROFORMULARIO]);
GO

-- Creating foreign key on [NROPROY] in table 'LISTADODEESTRATOS'
ALTER TABLE [dbo].[LISTADODEESTRATOS]
ADD CONSTRAINT [FK_LISTADOD_LISTESTRA_PROYECTO]
    FOREIGN KEY ([NROPROY])
    REFERENCES [dbo].[PROYECTO]
        ([NROPROY])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating foreign key on [NOMBRETIPOINV] in table 'PROYECTO'
ALTER TABLE [dbo].[PROYECTO]
ADD CONSTRAINT [FK_PROYECTO_ES_OBJETIVO]
    FOREIGN KEY ([NOMBRETIPOINV])
    REFERENCES [dbo].[OBJETIVOINVENTARIO]
        ([NOMBRETIPOINV])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_PROYECTO_ES_OBJETIVO'
CREATE INDEX [IX_FK_PROYECTO_ES_OBJETIVO]
ON [dbo].[PROYECTO]
    ([NOMBRETIPOINV]);
GO

-- Creating foreign key on [NROUSUARIO] in table 'PROYECTO'
ALTER TABLE [dbo].[PROYECTO]
ADD CONSTRAINT [FK_PROYECTO_CREA_USUARIO]
    FOREIGN KEY ([NROUSUARIO])
    REFERENCES [dbo].[USUARIO]
        ([NROUSUARIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_PROYECTO_CREA_USUARIO'
CREATE INDEX [IX_FK_PROYECTO_CREA_USUARIO]
ON [dbo].[PROYECTO]
    ([NROUSUARIO]);
GO

-- Creating foreign key on [TIPOPOYECTO_ID] in table 'PROYECTO'
ALTER TABLE [dbo].[PROYECTO]
ADD CONSTRAINT [FK_PROYECTO_ES_DE_TIP_TIPOPROY]
    FOREIGN KEY ([TIPOPOYECTO_ID])
    REFERENCES [dbo].[TIPOPROYECTO]
        ([TIPOPROYECTO_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_PROYECTO_ES_DE_TIP_TIPOPROY'
CREATE INDEX [IX_FK_PROYECTO_ES_DE_TIP_TIPOPROY]
ON [dbo].[PROYECTO]
    ([TIPOPOYECTO_ID]);
GO

-- Creating foreign key on [NOMTIPODISEMUEST] in table 'PROYECTO'
ALTER TABLE [dbo].[PROYECTO]
ADD CONSTRAINT [FK_PROYECTO_REALIZA_TIPODISE]
    FOREIGN KEY ([NOMTIPODISEMUEST])
    REFERENCES [dbo].[TIPODISENOMUESTRAL]
        ([NOMTIPODISEMUEST])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_PROYECTO_REALIZA_TIPODISE'
CREATE INDEX [IX_FK_PROYECTO_REALIZA_TIPODISE]
ON [dbo].[PROYECTO]
    ([NOMTIPODISEMUEST]);
GO

-- Creating foreign key on [NROUSUARIO] in table 'TRANSACCION'
ALTER TABLE [dbo].[TRANSACCION]
ADD CONSTRAINT [FK_TRANSACC_REGISTRA_USUARIO]
    FOREIGN KEY ([NROUSUARIO])
    REFERENCES [dbo].[USUARIO]
        ([NROUSUARIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_TRANSACC_REGISTRA_USUARIO'
CREATE INDEX [IX_FK_TRANSACC_REGISTRA_USUARIO]
ON [dbo].[TRANSACCION]
    ([NROUSUARIO]);
GO

-- Creating foreign key on [ESPECIE_CODESP] in table 'LISTADODEESPECIES'
ALTER TABLE [dbo].[LISTADODEESPECIES]
ADD CONSTRAINT [FK_LISTADODEESPECIES_ESPECIE]
    FOREIGN KEY ([ESPECIE_CODESP])
    REFERENCES [dbo].[ESPECIE]
        ([CODESP])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating foreign key on [PROYECTO_NROPROY] in table 'LISTADODEESPECIES'
ALTER TABLE [dbo].[LISTADODEESPECIES]
ADD CONSTRAINT [FK_LISTADODEESPECIES_PROYECTO]
    FOREIGN KEY ([PROYECTO_NROPROY])
    REFERENCES [dbo].[PROYECTO]
        ([NROPROY])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_LISTADODEESPECIES_PROYECTO'
CREATE INDEX [IX_FK_LISTADODEESPECIES_PROYECTO]
ON [dbo].[LISTADODEESPECIES]
    ([PROYECTO_NROPROY]);
GO

-- Creating foreign key on [PROYECTOCONTENIDO_NROPROY] in table 'PROYECTOSPORETAPA'
ALTER TABLE [dbo].[PROYECTOSPORETAPA]
ADD CONSTRAINT [FK_PROYECTOSPORETAPA_PROYECTOCONTENEDOR]
    FOREIGN KEY ([PROYECTOCONTENIDO_NROPROY])
    REFERENCES [dbo].[PROYECTO]
        ([NROPROY])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating foreign key on [PROYECTOCONTENDOR_NROPROY] in table 'PROYECTOSPORETAPA'
ALTER TABLE [dbo].[PROYECTOSPORETAPA]
ADD CONSTRAINT [FK_PROYECTOSPORETAPA_PROYECTOCONTENIDO]
    FOREIGN KEY ([PROYECTOCONTENDOR_NROPROY])
    REFERENCES [dbo].[PROYECTO]
        ([NROPROY])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_PROYECTOSPORETAPA_PROYECTOCONTENIDO'
CREATE INDEX [IX_FK_PROYECTOSPORETAPA_PROYECTOCONTENIDO]
ON [dbo].[PROYECTOSPORETAPA]
    ([PROYECTOCONTENDOR_NROPROY]);
GO

-- Creating foreign key on [LINEANOMADERABLES_LINEANMAD] in table 'USO'
ALTER TABLE [dbo].[USO]
ADD CONSTRAINT [FK_USO_LINEANOMADERABLES]
    FOREIGN KEY ([LINEANOMADERABLES_LINEANMAD])
    REFERENCES [dbo].[LINEANOMADERABLES]
        ([LINEANMAD])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating foreign key on [TIPODEUSO_NOMBRETIPOUSO] in table 'USO'
ALTER TABLE [dbo].[USO]
ADD CONSTRAINT [FK_USO_TIPODEUSO]
    FOREIGN KEY ([TIPODEUSO_NOMBRETIPOUSO])
    REFERENCES [dbo].[TIPODEUSO]
        ([NOMBRETIPOUSO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_USO_TIPODEUSO'
CREATE INDEX [IX_FK_USO_TIPODEUSO]
ON [dbo].[USO]
    ([TIPODEUSO_NOMBRETIPOUSO]);
GO

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------