//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SIFCA_DAL
{
    public partial class TIPODEUSO
    {
        public TIPODEUSO()
        {
            this.LINEANOMADERABLES = new HashSet<LINEANOMADERABLES>();
        }
    
        public string NOMBRETIPOUSO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<LINEANOMADERABLES> LINEANOMADERABLES { get; set; }
    }
    
}
