//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SIFCA_DAL
{
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.FORMULARIO = new HashSet<FORMULARIO>();
            this.PROYECTO = new HashSet<PROYECTO>();
            this.TRANSACCION = new HashSet<TRANSACCION>();
        }
    
        public System.Guid NROUSUARIO { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public string NOMBREUSUARIO { get; set; }
        public string CONTRASENA { get; set; }
        public decimal CEDULA { get; set; }
    
        public virtual ICollection<FORMULARIO> FORMULARIO { get; set; }
        public virtual ICollection<PROYECTO> PROYECTO { get; set; }
        public virtual ICollection<TRANSACCION> TRANSACCION { get; set; }
    }
    
}
