//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SIFCA_DAL
{
    public partial class INVENTARIO
    {
        public decimal CODCALIDAD { get; set; }
        public decimal NROPROY { get; set; }
        public string ESTADO { get; set; }
        public decimal CODEST { get; set; }
        public decimal CODESP { get; set; }
        public decimal CODETAPA { get; set; }
        public System.Guid NROEST { get; set; }
        public decimal PARCELA { get; set; }
        public decimal NROARB { get; set; }
        public decimal CAP { get; set; }
        public decimal DAP { get; set; }
        public decimal ALTCOMER_M { get; set; }
        public decimal ALTTOT_M { get; set; }
        public decimal AREABASAL { get; set; }
        public decimal VOLCOM { get; set; }
        public decimal VOLTOT { get; set; }
    
        public virtual CALIDAD CALIDAD { get; set; }
        public virtual ESPECIE ESPECIE { get; set; }
        public virtual ESTACION ESTACION { get; set; }
        public virtual ESTADOSANITARIO ESTADOSANITARIO { get; set; }
        public virtual ESTRATO ESTRATO { get; set; }
        public virtual ETAPA ETAPA { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
    }
    
}
