//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SIFCA_DAL
{
    public partial class LINEAREGENERACION
    {
        public Nullable<decimal> NROARB { get; set; }
        public Nullable<decimal> LATIZAL { get; set; }
        public Nullable<decimal> BRINZAL { get; set; }
        public System.Guid LINEAREGEN { get; set; }
        public System.Guid NROFORMULARIO { get; set; }
        public System.Guid CODESP { get; set; }
    
        public virtual ESPECIE ESPECIE { get; set; }
        public virtual FORMULARIO FORMULARIO { get; set; }
    }
    
}
