//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SIFCA_DAL
{
    public partial class REGENERACION
    {
        public System.Guid NROEST { get; set; }
        public decimal PARCELA { get; set; }
        public Nullable<decimal> NROARB { get; set; }
        public Nullable<decimal> LATIZAL { get; set; }
        public Nullable<decimal> BRINZAL { get; set; }
        public decimal CODEST { get; set; }
        public decimal CODETAPA { get; set; }
        public decimal NROPROY { get; set; }
        public decimal CODESP { get; set; }
    
        public virtual ESPECIE ESPECIE { get; set; }
        public virtual ESTACION ESTACION { get; set; }
        public virtual ESTRATO ESTRATO { get; set; }
        public virtual ETAPA ETAPA { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
    }
    
}
