//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SIFCA_DAL
{
    public partial class TIPOPROYECTO
    {
        public TIPOPROYECTO()
        {
            this.PROYECTO = new HashSet<PROYECTO>();
        }
    
        public decimal TIPOPROYECTO_ID { get; set; }
        public string DESCRIPCION { get; set; }
        public string NOMBRETIPOPROYECTO { get; set; }
    
        public virtual ICollection<PROYECTO> PROYECTO { get; set; }
    }
    
}
