//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SIFCA_DAL
{
    public partial class FORMULA
    {
        public FORMULA()
        {
            this.PROYECTO = new HashSet<PROYECTO>();
            this.VARIABLE = new HashSet<VARIABLE>();
        }
    
        public System.Guid NROFORMULA { get; set; }
        public System.Guid NROTIPOFORMULA { get; set; }
        public string EXPRESION { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual TIPOFORMULA TIPOFORMULA { get; set; }
        public virtual ICollection<PROYECTO> PROYECTO { get; set; }
        public virtual ICollection<VARIABLE> VARIABLE { get; set; }
    }
    
}
