//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SIFCA_DAL
{
    public partial class LINEAINVENTARIO
    {
        public System.Guid LINEAINV { get; set; }
        public decimal CODCALIDAD { get; set; }
        public System.Guid NROFORMULARIO { get; set; }
        public string ESTADO { get; set; }
        public System.Guid CODESP { get; set; }
        public decimal NROARB { get; set; }
        public decimal ALTCOMER_M { get; set; }
        public decimal ALTTOT_M { get; set; }
        public decimal AREABASAL { get; set; }
        public decimal VOLCOM { get; set; }
        public decimal VOLTOT { get; set; }
        public string TIPOARBOL { get; set; }
        public decimal CAP { get; set; }
        public decimal DAP { get; set; }
    
        public virtual CALIDAD CALIDAD { get; set; }
        public virtual ESPECIE ESPECIE { get; set; }
        public virtual ESTADOSANITARIO ESTADOSANITARIO { get; set; }
        public virtual FORMULARIO FORMULARIO { get; set; }
    }
    
}
