//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SIFCA_DAL
{
    public partial class FORMULARIO
    {
        public FORMULARIO()
        {
            this.LINEAINVENTARIO = new HashSet<LINEAINVENTARIO>();
            this.LINEANOMADERABLES = new HashSet<LINEANOMADERABLES>();
            this.LINEAREGENERACION = new HashSet<LINEAREGENERACION>();
        }
    
        public System.Guid NROFORMULARIO { get; set; }
        public Nullable<decimal> CODEST { get; set; }
        public System.Guid NROUSUARIO { get; set; }
        public System.Guid NROPROY { get; set; }
        public System.DateTime FECHACREACION { get; set; }
        public Nullable<System.DateTime> HORAINICIO { get; set; }
        public Nullable<System.DateTime> HORAFINAL { get; set; }
        public decimal PARCELA { get; set; }
        public decimal LINEA { get; set; }
        public Nullable<decimal> COORDENADAX { get; set; }
        public Nullable<decimal> COORDENADAY { get; set; }
    
        public virtual ESTRATO ESTRATO { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<LINEAINVENTARIO> LINEAINVENTARIO { get; set; }
        public virtual ICollection<LINEANOMADERABLES> LINEANOMADERABLES { get; set; }
        public virtual ICollection<LINEAREGENERACION> LINEAREGENERACION { get; set; }
    }
    
}
