//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SIFCA_DAL
{
    public partial class PROYECTO
    {
        public PROYECTO()
        {
            this.FORMULARIO = new HashSet<FORMULARIO>();
            this.LISTADODEESTRATOS = new HashSet<LISTADODEESTRATOS>();
            this.PROYECTOSPORETAPA = new HashSet<PROYECTOSPORETAPA>();
            this.PROYECTOSPORETAPA1 = new HashSet<PROYECTOSPORETAPA>();
            this.ESPECIE = new HashSet<ESPECIE>();
            this.LISTADODECOSTOS = new HashSet<LISTADODECOSTOS>();
        }
    
        public System.Guid NROPROY { get; set; }
        public System.Guid NROUSUARIO { get; set; }
        public string NOMBRETIPOINV { get; set; }
        public string NOMTIPODISEMUEST { get; set; }
        public System.Guid NROFORMULA { get; set; }
        public string LUGAR { get; set; }
        public decimal NUMEROPARCELAS { get; set; }
        public decimal NUMEROPARCELASAMUESTREAR { get; set; }
        public decimal TAMANO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal SUPTOT { get; set; }
        public decimal INTMUE { get; set; }
        public decimal SUPMUE { get; set; }
        public decimal LIMITINFDAP { get; set; }
        public decimal AREAFUSTALESPORPARCELA { get; set; }
        public decimal FACTORDEFORMA { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal ETAPA { get; set; }
        public string TIPOPROYECTO { get; set; }
        public decimal CONFIANZA { get; set; }
    
        public virtual FORMULA FORMULA { get; set; }
        public virtual ICollection<FORMULARIO> FORMULARIO { get; set; }
        public virtual ICollection<LISTADODEESTRATOS> LISTADODEESTRATOS { get; set; }
        public virtual OBJETIVOINVENTARIO OBJETIVOINVENTARIO { get; set; }
        public virtual ICollection<PROYECTOSPORETAPA> PROYECTOSPORETAPA { get; set; }
        public virtual ICollection<PROYECTOSPORETAPA> PROYECTOSPORETAPA1 { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual TIPODISENOMUESTRAL TIPODISENOMUESTRAL { get; set; }
        public virtual ICollection<ESPECIE> ESPECIE { get; set; }
        public virtual ICollection<LISTADODECOSTOS> LISTADODECOSTOS { get; set; }
    }
    
}
