//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SIFCA_DAL
{
    public partial class VARIABLE
    {
        public VARIABLE()
        {
            this.FORMULA = new HashSet<FORMULA>();
        }
    
        public System.Guid NROVARIABLE { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<FORMULA> FORMULA { get; set; }
    }
    
}
