//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SIFCA_ENTITIES
{
    public partial class ESTADOSANITARIO
    {
        public ESTADOSANITARIO()
        {
            this.INVENTARIO = new HashSet<INVENTARIO>();
        }
    
        public string ESTADO { get; set; }
        public string DESCRIPESTADO { get; set; }
    
        public virtual ICollection<INVENTARIO> INVENTARIO { get; set; }
    }
    
}
