//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SIFCA_ENTITIES
{
    public partial class ETAPA
    {
        public ETAPA()
        {
            this.INVENTARIO = new HashSet<INVENTARIO>();
            this.REGENERACION = new HashSet<REGENERACION>();
        }
    
        public decimal CODETAPA { get; set; }
        public string DESCRIPETAPA { get; set; }
    
        public virtual ICollection<INVENTARIO> INVENTARIO { get; set; }
        public virtual ICollection<REGENERACION> REGENERACION { get; set; }
    }
    
}
